config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :comments, only: [:create]
  resources :installations, only: [:index, :show] do
    resources :pull_requests, only: [:index]
  end
  resource :installations, only: [:new]
  resource :callback, only: [:show], controller: :callback
  resource :githubapp_auth, only: [:create], controller: :githubapp_auth
  resources :select_repos, only: [:index]
  resources :users, only: [:destroy]
  namespace :api, format: :json do
    resources :webhook, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/installation.rb
class Installation < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :installations
end

app/controllers/api/auth_controller.rb
module Api
  class AuthController < ApplicationController
    skip_before_action :verify_authenticity_token

    def create
      render json: {test: 'test'}, status: :ok
    end
  end
end

app/controllers/api/webhook_controller.rb
module Api
  class WebhookController < ApplicationController
    skip_before_action :verify_authenticity_token

    def create
      #dd
      binding.pry
      render json: {test: 'test'}, status: :ok
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def authorize_user
    unless current_user.present?
      redirect_to root_path, alert: 'Not authorized!'
    end
  end
end

app/controllers/callback_controller.rb
class CallbackController < ApplicationController
  def show
    user = GithubApps::OauthCreator.user(params[:code], params[:state])
    if user.present?
      session[:user_id] = user.id
      redirect_to select_repos_path
    else
      redirect_to root_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    if create_comment
      redirect_to params[:referrer_path], notice: 'Comment successfully created!'
    else
      redirect_to params[:referrer_path], alert: 'Something went wrong!'
    end
  end

  private

  def create_comment
    GithubApps::CommentCreator
      .create(params[:installation_id], params[:path], params[:body])
  end
end

app/controllers/githubapp_auth_controller.rb
class GithubappAuthController < ApplicationController
  def create
    url = [
      ENV['GITHUB_APPS_AUTH_URL'],
      "?client_id=#{ENV['GITHUB_APPS_CLIENT_ID']}",
      "&state=randomdupa"
    ].join

    redirect_to url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/installations_controller.rb
class InstallationsController < ApplicationController
  def index
    @installations = GithubApps::AppInstallationsParser.installations
  end

  def new
    GithubApps::InstallationCreator
      .create(current_user, params[:installation_id])
    redirect_to root_path
  end

  def show
    @repositories =
      GithubApps::InstallationRepositoriesParser.repositories(params[:id])
  end
end

app/controllers/pull_requests_controller.rb
class PullRequestsController < ApplicationController
  def index
    set_request_uri
    @pulls = repo.pulls
  end

  private

  def repo
    @repo ||=
      GithubApps::Klasses::Repo.new(
        params.require(:repo)
              .permit(:id, :name, :owner, :installation_id)
              .merge!(installation_id: installation_id)
      )
  end

  def installation_id
    @installation_id ||= params[:installation_id]
  end

  def set_request_uri
    @request_uri ||= request.env['REQUEST_URI']
  end
end

app/controllers/select_repos_controller.rb
class SelectReposController < ApplicationController
  before_action :authorize_user

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: 'Successfully logged out!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Home</h1>

<%= link_to 'Sign up via Github Apps', githubapp_auth_path, method: :post %>

app/views/home/show.html.erb
<h1>show</h1>

app/views/installations/index.html.erb
<h1>Installations</h1>
<ul>
  <%- @installations.each do |login, installation_id| %>
    <li>Login: <%= login %> | <%= link_to installation_id, installation_path(id: installation_id) %></li>
  <% end %>
</ul>

app/views/installations/show.html.erb
<h1>Repositories</h1>

<ul>
  <%- @repositories.each do |key, value| %>
    <li>Login: <%= key %> | <%= link_to 'show', installation_pull_requests_path(installation_id: params[:id], repo: value) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Githubappstest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- navbar -->
    <div class='navbar'>
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Installations', installations_path %></li>
        <% if current_user.present? %>
          <li><%= link_to 'Add new repo', select_repos_path %></li>
          <li><%= link_to 'Sign Out', user_path(current_user), method: :delete %></li>
        <% end %>
      </ul>
    </div>
    <!-- navbar -->

    <!-- notification -->
    <% if flash[:notice].present? %>
      <div class='notify notice'><%= flash[:notice] %></div>
    <% end %>

    <% if flash[:alert].present? %>
      <div class='notify alert'><%= flash[:alert] %></div>
    <% end %>
    <!-- notification -->

    <%= yield %>
  </body>
</html>

app/views/pull_requests/index.html.erb
<h1>PRS</h1>


<%- @pulls.each do |pull_request| %>
  <div class='pr-content'>
    <div class='pr-title'>Title: <%= pull_request.title %></div>
    <% if pull_request.comments.present? %>
      <h3>Comments:</h5>
      <div class='pr-comments-content'>
          <%- pull_request.comments.each do |comment| %>
            <div class='pr-comment-conent'>
              <div class='pr-comments-author'><%= comment.user %></div>
              <div class='pr-comments-body'><%= comment.body %></div>
            </div>
          <% end %>
      </div>
    <% end %>

    <h3>Add Comment:</h3>
    <%= form_tag comments_path do %>
      <%= hidden_field_tag 'installation_id', @installation_id %>
      <%= hidden_field_tag 'referrer_path', @request_uri %>
      <%= hidden_field_tag 'path', pull_request.comments_url %>

      <%= label_tag 'Body:' %>
      <%= text_area_tag 'body' %>
      <br>
      <%= submit_tag 'Add' %>
    <% end %>
  </div>
<% end %>

app/views/select_repos/index.html.erb
<h1>Please select repo:</h1>
<%= link_to 'Select', ENV['NEW_INSTALLATION_URL'] %>